### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function entity_property_list_extract_type

### ISSUE THREAD

**Issue by sds-i** [backdrop-contrib/entity_token#2] opened 2020-04-08 09:52 UTC
After activating the moduel I am getting the follwoing error:

**( ! )  Fatal error: Uncaught Error: Call to undefined function  entity_property_list_extract_type() in  C:\wamp64\www\ [my-site] \modules\entity_token\entity_token.tokens.inc  on line 218
( ! ) Error: Call to undefined function entity_property_list_extract_type() in C:\wamp64\www\ [my-site] \modules\entity_token\entity_token.tokens.inc on line 218**
Call Stack
1 | 1.1904 | 5922624 | _backdrop_exception_handler(  ) | ...\bootstrap.inc:0
2 | 1.1905 | 5923208 | _backdrop_log_error(  ) | ...\bootstrap.inc:2964
3 | 1.1975 | 5927952 | theme(  ) | ...\errors.inc:252
4 | 1.1995 | 5924288 | metatag_preprocess_maintenance_page(  ) | ...\theme.inc:1118
5 | 1.1995 | 5924288 | metatag_prepare_tags(  ) | ...\metatag.module:2109
6 | 1.2030 | 5927528 | metatag_metatags_view(  ) | ...\metatag.module:1767
7 | 1.2031 | 5928376 | BackdropTitleMetaTag->getElement(  ) | ...\metatag.module:1219
8 | 1.2031 | 5928376 | BackdropTitleMetaTag->getValue(  ) | ...\metatag.inc:421
9 | 1.2039 | 5929200 | token_replace(  ) | ...\metatag.inc:312
10 | 1.2100 | 5935776 | token_generate(  ) | ...\token.inc:86
11 | 1.2100 | 5936152 | module_invoke_all(  ) | ...\token.inc:177
12 | 1.2100 | 5938288 | entity_token_tokens(  ) | ...\module.inc:960

Deactivating the module the fatal error disappears. 

Initially I was under the impression this is related to this error that came up at the same time - but maybe just due to activating the two modules at the same time.

`Notice: Undefined property: stdClass::$language in userpoints_tokens() (line 468 of C:\wamp64\www\ [my-site] \modules\userpoints\userpoints.module).`
I will report this second error in the right place now.

**Comment by sds-i** [comment] 2020-04-08 09:57
Actually the error is more fundamental:

**( ! )  Fatal error: Uncaught Error: Call to undefined function  entity_property_list_extract_type() in  C:\wamp64\www\ [my-site] \modules\entity_token\entity_token.tokens.inc  on line 218
( ! ) Error: Call to undefined function entity_property_list_extract_type() in C:\wamp64\www\ [my-site] \modules\entity_token\entity_token.tokens.inc on line 218**

Call Stack
--
1 | 1.1904 | 5922624 | _backdrop_exception_handler(  ) | ...\bootstrap.inc:0
2 | 1.1905 | 5923208 | _backdrop_log_error(  ) | ...\bootstrap.inc:2964
3 | 1.1975 | 5927952 | theme(  ) | ...\errors.inc:252
4 | 1.1995 | 5924288 | metatag_preprocess_maintenance_page(  ) | ...\theme.inc:1118
5 | 1.1995 | 5924288 | metatag_prepare_tags(  ) | ...\metatag.module:2109
6 | 1.2030 | 5927528 | metatag_metatags_view(  ) | ...\metatag.module:1767
7 | 1.2031 | 5928376 | BackdropTitleMetaTag->getElement(  ) | ...\metatag.module:1219
8 | 1.2031 | 5928376 | BackdropTitleMetaTag->getValue(  ) | ...\metatag.inc:421
9 | 1.2039 | 5929200 | token_replace(  ) | ...\metatag.inc:312
10 | 1.2100 | 5935776 | token_generate(  ) | ...\token.inc:86
11 | 1.2100 | 5936152 | module_invoke_all(  ) | ...\token.inc:177
12 | 1.2100 | 5938288 | entity_token_tokens(  ) | ...\module.inc:960

**Comment by docwilmot** [comment] 2020-04-08 21:26
Weird that this was missed without causing errors on my site.

**Comment by docwilmot** [comment] 2020-04-08 21:27
PLease try again

**Comment by sds-i** [comment] 2020-04-09 08:09
Hi, ok. 
I just activated Entity Token module again, I cleared all caches and I had the same failure.
I deactivated and uninstalled the module and the error went. I then activated the mudle once more and the error returned. 
Just deactivating the module resolves the error. Uninstalling is not necessary.
Let me know what other info I can send you to help pinpointing the problem. 

I activated quite a few modules. A list is enclosed.

Here is the extract from the php error log:
[Modules_installed_activated.zip](https://github.com/backdrop-contrib/entity_token/files/4454838/Modules_installed_activated.zip)


PHP Fatal error:  Uncaught Error: Call to undefined function entity_property_list_extract_type() in C:\wamp64\www\.....\modules\entity_token\entity_token.tokens.inc:218
Stack trace:
#0 C:\wamp64\www\spondeo.network\core\includes\module.inc(960): entity_token_tokens('current-page', Array, Array, Array)
#1 C:\wamp64\www\spondeo.network\core\includes\token.inc(177): module_invoke_all('tokens', 'current-page', Array, Array, Array)
#2 C:\wamp64\www\spondeo.network\core\includes\token.inc(86): token_generate('current-page', Array, Array, Array)
#3 C:\wamp64\www\.....\modules\metatag\metatag.inc(312): token_replace('[site:name] | [...', Array, Array)
#4 C:\wamp64\www\spondeo.network\modules\metatag\metatag.inc(421): BackdropTextMetaTag->getValue(Array)
#5 C:\wamp64\www\spondeo.network\modules\metatag\metatag.module(1219): BackdropTitleMetaTag->getElement(Array)
#6 C:\wamp64\www\spondeo.network\modules\metatag\metatag.module(1767): metatag_metatags_view('global:frontpag...', Array)
#7 C:\wamp64\www\spondeo.network\ in C:\wamp64\www\.....\modules\entity_token\entity_token.tokens.inc on line 218

List of modules of the site is enclosed

**Comment by olafgrabienski** [comment] 2020-04-10 10:01
Confirmed. I just installed the module and got the same error. It appeared when I was visiting a node.

**Comment by indigoxela** [comment] 2020-04-10 11:06
function entity_property_list_extract_type() in D7 is provided by the Entity API module.

That function isn't complicated, it should be easy to do the same in entity_token (Backdrop module):

https://git.drupalcode.org/project/entity/-/blob/7.x-1.x/includes/entity.property.inc#L350

**Comment by indigoxela** [comment] 2020-04-10 11:10
`Notice: Undefined property: stdClass::$language`

@sds-i This should be reported in the userpoints issue queue.

**Comment by sds-i** [comment] 2020-04-10 12:08
@indigoxela - I did - thanks for the help finding my way around

**Comment by ghost** [comment] 2020-04-22 08:32
Looks like @docwilmot fixed this: https://github.com/backdrop-contrib/entity_token/blob/1.x-1.x/entity_token.tokens.inc#L218

@sds-i You'll need to use the latest version of the code to see the fix working (or make the change manually yourself) until @docwilmot releases a new version of the module with the fix included.

For the record I experienced this and applying the fix manually fixed it for me. Closing therefore as fixed.

**Closed as completed by ghost** 2020-04-22 08:32 UTC
